{
	"id": "CVE-2021-29617",
	"description": "A security issue has been found in TensorFlow before version 2.4.2. An attacker can cause a denial of service via `CHECK`-fail in `tf.strings.substr` with invalid arguments.",
	"hardware": [],
	"software": [
		{
			"name": "tensorflow",
			"platform": "archlinux",
			"version": "< 2.5.0-1"
		}
	],
	"references": [
		"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-mmq6-q8r3-48fm",
		"https://github.com/tensorflow/tensorflow/commit/890f7164b70354c57d40eda52dcdd7658677c09f",
		"https://github.com/tensorflow/issues/46974",
		"https://github.com/tensorflow/issues/46900"
	],
	"severity": "low",
	"state": "invalid",
	"_is_edited": false
}