{
	"id": "CVE-2020-24119",
	"description": "A heap buffer overflow read was discovered in upx 4.0.0, because the check in p_lx_elf.cpp is not perfect.\n\nA heap buffer overflow read was discovered in upx 3.96 because the check in p_lx_elf.cpp is not perfect.",
	"hardware": [],
	"software": [
		{
			"vendor": "archlinux",
			"product": "upx",
			"version": "<= 3.96-2"
		}
	],
	"references": [
		"https://github.com/upx/upx/issues/388",
		"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VSQRO7YC72PSYDQG4PQLQYXZTZE3B4YV/",
		"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JE54WKVU7MATB4WZD3MJFBAHFRJ3NTQX/",
		"https://github.com/upx/upx/files/4958990/poc-heap-buffer-overflow-get_le32.tar.gz",
		"https://github.com/upx/upx/commit/87b73e5cfdc12da94c251b2cd83bb01c7d9f616c"
	],
	"_edited_": false,
	"severity": "Medium"
}