{
	"name": "AVG-1663",
	"packages": [
		"python2-pygments"
	],
	"status": "Unknown",
	"severity": "Low",
	"type": "denial of service",
	"affected": "2.5.2-2",
	"fixed": null,
	"ticket": null,
	"issues": [
		"CVE-2021-27291",
		"CVE-2021-20270"
	],
	"advisories": [],
	"references": [
		"https://pygments.org/docs/changelog/#version-2-6"
	],
	"notes": "python-pygments 2.5.2 was the last version to support Python 2.x, so this issue is not going to get fixed."
}