{
	"identifier": "CVE-2020-7134",
	"description": "A remote access to sensitive data vulnerability was discovered in HPE IOT + GCP version(s): 1.4.0, 1.4.1, 1.4.2, 1.2.4.2.",
	"type": "network",
	"severity": "medium",
	"state": "published",
	"datetime": "2020-04-24T17:15:13Z",
	"is_edited": false,
	"hardware": [],
	"software": [],
	"products": [
		{
			"name": "hpe-iot-gcp",
			"version": "1.2.4.2",
			"architecture": "any",
			"vendor": "hp",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "hpe-iot-gcp",
			"version": "1.4.0",
			"architecture": "any",
			"vendor": "hp",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "hpe-iot-gcp",
			"version": "1.4.1",
			"architecture": "any",
			"vendor": "hp",
			"type": "software",
			"is_edited": false,
			"aliases": []
		},
		{
			"name": "hpe-iot-gcp",
			"version": "1.4.2",
			"architecture": "any",
			"vendor": "hp",
			"type": "software",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US\u0026docId=emr_na-hpesbhf03947en_us"
	],
	"weaknesses": []
}