{
	"identifier": "USN-4204-1",
	"description": "",
	"type": "none",
	"severity": "none",
	"state": "invalid",
	"datetime": "0000-00-00T00:00:00Z",
	"is_edited": false,
	"hardware": [],
	"software": [
		{
			"name": "python-psutil-doc",
			"version": "\u003c 0:5.4.2-1ubuntu0.1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python-psutil",
			"version": "\u003c 0:5.4.2-1ubuntu0.1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python3-psutil",
			"version": "\u003c 0:5.4.2-1ubuntu0.1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python-psutil-doc",
			"version": "\u003c 0:3.4.2-1ubuntu0.1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python-psutil",
			"version": "\u003c 0:3.4.2-1ubuntu0.1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python3-psutil",
			"version": "\u003c 0:3.4.2-1ubuntu0.1",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		}
	],
	"products": [],
	"references": [
		"https://ubuntu.com/security/notices/USN-4204-1"
	],
	"weaknesses": []
}