{
	"name": "CVE-2021-20213",
	"description": "A flaw was found in Privoxy in versions before 3.0.29. Dereference of a NULL-pointer that could result in a crash if accept-intercepted-requests was enabled, Privoxy failed to get the request destination from the Host header and a memory allocation failed.",
	"packages": [
		{
			"name": "privoxy",
			"releases": {
				"bookworm": {
					"status": "resolved",
					"repositories": {
						"bookworm": "3.0.33-1"
					},
					"fixed_version": "3.0.29-1",
					"urgency": "not yet assigned"
				},
				"bullseye": {
					"status": "resolved",
					"repositories": {
						"bullseye": "3.0.32-2+deb11u1"
					},
					"fixed_version": "3.0.29-1",
					"urgency": "not yet assigned"
				},
				"buster": {
					"status": "resolved",
					"repositories": {
						"buster": "3.0.28-2+deb10u2"
					},
					"fixed_version": "3.0.28-2+deb10u1",
					"urgency": "not yet assigned"
				},
				"sid": {
					"status": "resolved",
					"repositories": {
						"sid": "3.0.33-1"
					},
					"fixed_version": "3.0.29-1",
					"urgency": "not yet assigned"
				},
				"stretch": {
					"status": "resolved",
					"repositories": {
						"stretch": "3.0.26-3",
						"stretch-security": "3.0.26-3+deb9u3"
					},
					"fixed_version": "3.0.26-3+deb9u1",
					"urgency": "not yet assigned"
				}
			}
		}
	],
	"scope": "local"
}