{
	"name": "CVE-2021-20272",
	"description": "A flaw was found in privoxy before 3.0.32. An assertion failure could be triggered with a crafted CGI request leading to server crash.",
	"packages": [
		{
			"name": "privoxy",
			"releases": {
				"bookworm": {
					"status": "resolved",
					"repositories": {
						"bookworm": "3.0.33-1"
					},
					"fixed_version": "3.0.32-1",
					"urgency": "not yet assigned"
				},
				"bullseye": {
					"status": "resolved",
					"repositories": {
						"bullseye": "3.0.32-2+deb11u1"
					},
					"fixed_version": "3.0.32-1",
					"urgency": "not yet assigned"
				},
				"buster": {
					"status": "resolved",
					"repositories": {
						"buster": "3.0.28-2+deb10u2"
					},
					"fixed_version": "3.0.28-2+deb10u1",
					"urgency": "not yet assigned"
				},
				"sid": {
					"status": "resolved",
					"repositories": {
						"sid": "3.0.33-1"
					},
					"fixed_version": "3.0.32-1",
					"urgency": "not yet assigned"
				},
				"stretch": {
					"status": "resolved",
					"repositories": {
						"stretch": "3.0.26-3",
						"stretch-security": "3.0.26-3+deb9u3"
					},
					"fixed_version": "3.0.26-3+deb9u2",
					"urgency": "not yet assigned"
				}
			}
		}
	],
	"scope": "local"
}