{
	"name": "CVE-2013-4260",
	"description": "lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook does not run due to an error, allows local users to overwrite arbitrary files via a symlink attack on a retry file with a predictable name in /var/tmp/ansible/.",
	"packages": [
		{
			"name": "ansible",
			"releases": {
				"bookworm": {
					"status": "resolved",
					"repositories": {
						"bookworm": "5.5.0-1"
					},
					"fixed_version": "0",
					"urgency": "unimportant"
				},
				"bullseye": {
					"status": "resolved",
					"repositories": {
						"bullseye": "2.10.7+merged+base+2.10.8+dfsg-1"
					},
					"fixed_version": "0",
					"urgency": "unimportant"
				},
				"buster": {
					"status": "resolved",
					"repositories": {
						"buster": "2.7.7+dfsg-1+deb10u1",
						"buster-security": "2.7.7+dfsg-1+deb10u1"
					},
					"fixed_version": "0",
					"urgency": "unimportant"
				},
				"sid": {
					"status": "resolved",
					"repositories": {
						"sid": "5.5.0-1"
					},
					"fixed_version": "0",
					"urgency": "unimportant"
				},
				"stretch": {
					"status": "resolved",
					"repositories": {
						"stretch": "2.2.1.0-2+deb9u1",
						"stretch-security": "2.2.1.0-2+deb9u3"
					},
					"fixed_version": "0",
					"urgency": "unimportant"
				}
			}
		}
	],
	"scope": "local"
}